// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PROJECT_NAME = 'whats_app';
  static const String PROJECT_VERSION = '1.0.0+1';
  static const String CAMERA = 'assets/images/Camera.png';
  static const String MIC = 'assets/images/Mic.png';
  static const String PHONE = 'assets/images/Phone.png';
  static const String SEND = 'assets/images/Send.png';
  static const String BACKGROUND_IMAGE = 'assets/images/background_image.png';
  static const String PROFILE_IMAGE = 'assets/images/profile_image.jpg';
  static const String ROUTE_IMAGE = 'assets/images/route_image.jpg';
  static const String VIDEO = 'assets/images/video.png';
}
